### ISSUE TITLE
Same Request: Auto-delete temporary containers per session

### ISSUE THREAD

**Issue by EstherMoellman** [zncoder/confiner#3]
Hi @zncoder  , it's been a while since last year, here I'm again, today please with a repeated request.

The problem is that your add-on (sometimes) doesn't delete temporary containers.
I can see same temporary containers accumulating and accumulating over the time, and your add-on is opening temporary containers over these same undeleted temporary containers.

I'm using your add-on with this other add-on: https://addons.mozilla.org/en-US/firefox/addon/tabs-to-bookmark-groups/
I'm not an expert, but from my ignorance, I don't believe TabsToBookmarkGroups add-on is the culprit, because it works well with other temporary containers.

Anyway, please my request is very simple:

1) During same browser session, always keep same temporary container, until a new tab is opened with same url or different url.

2) When browser session is finished and browser closes, all temporary containers are deleted. Every new browser session should have zero saved temporary containers. By the way, that's the meaning of "temporary"... it'll be alive, until browser closes.

Hope you can do it! It'll be fantastic.
Thousand thanks to you in advance!

Big hug! : )

**Comment by zncoder** [comment]
Hi,

Unused temporary containers are deleted in 1h. This add-on starts to reuse
the names once the number of temporary containers exceeds certain
threshold. But the containers should be different even if the names are the
same.

This add-on does not delete temporary containers when browser is closed,
because the temporary containers are associated with the tabs. They will
stay unless the tabs are closed. I don't think Firefox allows deletion of a
container if the container is still used by a tab.

Thanks,
